on: [push, pull_request]

name: Run tests

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: install packages
      run: |
        pip install virtualenv --upgrade
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests
      run: ./test.sh && codecov
